concurrent = 1
check_interval = 0
shutdown_timeout = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "docker-stable"
  url = "https://www.direbo.ru"
  id = 1
  token = "insert_token_here"
  token_obtained_at = 2024-04-11T23:44:02Z
  token_expires_at = 0001-01-01T00:00:00Z
  executor = "docker"
  [runners.custom_build_dir]
  [runners.cache]
    MaxUploadedArchiveSize = 0
    [runners.cache.s3]
    [runners.cache.gcs]
    [runners.cache.azure]
  [runners.docker]
    tls_verify = false
    image = "docker:stable"
    privileged = false
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/var/run/docker.sock:/var/run/docker.sock", "/cache"]
    network_mode = "gitlab-network"
    shm_size = 0
    network_mtu = 0
    allowed_pull_policies = ["if-not-present", "always"]
    pull_policy = "if-not-present"
    helper_image = "gitlab/gitlab-runner-helper:x86_64-v16.10.0"
